name: 🚀 Deploy WordPress Site

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    name: Build and Deploy
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Sync files
        uses: SamKirkland/FTP-Deploy-Action@v4.3.4
        with:
          server: ${{ secrets.MAIDENS_FTP_SERVER }}
          username: ${{ secrets.MAIDENS_FTP_USERNAME }}
          password: ${{ secrets.MAIDENS_FTP_PASSWORD }}
          local-dir: ./wp-content/
          server-dir: /wp-content/themes/maidens-and-ravens/
